### ISSUE TITLE
 i just update xcode to 11 , toolTip working fine m but now crashing

### ISSUE THREAD

**Issue by Adeelhussainios** [calmcom/SexyTooltip#11]
After updating xcode to 11 , we are getting crash on last line

- (void)observeValueForKeyPath:(NSString *)keyPath
                      ofObject:(id)object
                        change:(NSDictionary *)change
                       context:(void *)context
{
    if ([keyPath isEqualToString:@"position"]) {
        if (_attachedToView
            && object == self.fromView.layer)
        {
            NSValue *new = change[NSKeyValueChangeNewKey];
            NSValue *old = change[NSKeyValueChangeOldKey];
            CGRect newFrame = [new isKindOfClass:[NSNull class]] ? CGRectZero : [new CGRectValue];

**Comment by ctscoville** [comment]
Yes, we encountered the crash as well. We're looking into a solution on just removing the position observer on the tooltips.  That fixes the crash for sure, but has the downside of not allowing the tooltip to move with the view it's attached to.  At Calm, we don't need that behavior, but I'm curious if that's something other people have found useful.

**Comment by apleton** [comment]
Same crash here. In my case it happens when the device orientation changes. Any hope for a fix ?

**Comment by ctscoville** [comment]
We just merged the PR that should fix this.

**Comment by failynsedik** [comment]
We're experiencing the same crash now. Exception breakpoint stops at `CGRect newFrame = [new isKindOfClass:[NSNull class]] ? CGRectZero : [new CGRectValue];` and has a crash reason of **"Cannot get value with size 32. The type encoded as {CGPoint=dd} is expected to be 16 bytes"**. In our case, it happens while the tooltip is open, then the user scrolls the screen.
