### ISSUE TITLE
"Tooltip couldn't fit with any of the permitted arrow directions, removing margin and using highest priority arrow direction"

### ISSUE THREAD

**Issue by benliong** [calmcom/SexyTooltip#4]
I keep getting 'Tooltip couldn't fit with any of the permitted arrow directions, removing margin and using highest priority arrow direction' when presenting from a view that takes up say half the screen.  Any advice?

**Comment by tsheaff** [comment]
@benliong If you're willing to share a code sample I'd be happy to dig in.  Most ideal would be a mini-project from scratch that minimally reproduces the issue you're observing.

After that, we can figure out how to solve the problem.

Cheers,

--Tyler

**Comment by tsheaff** [comment]
btw, that warning is being triggered [here](https://github.com/calmcom/SexyTooltip/blob/9db826b27c526970b206a82c1b56c10b3bff75e1/SexyTooltip/SexyTooltip.m#L345) which implies that either your width or height is zero. Does your tooltip have content inside it?

**Comment by jpmcglone** [comment]
@benliong something to keep in mind is that your tooltip also has a corner radius!  So, if the center of the frame / view you are trying to point at is very close to the edge of the screen, it may not have enough room given your tooltip's cornerRadius + margin.  I ran into this issue last week :P

I recommend lowering the margin first.

Also, you mentioned your view takes up half the screen, so I'd imagine there _is_ space for your tooltip!

I recommend adding all of the arrow directions and reporting back.

**swift:**

``` swift
tooltip.permittedArrowDirections = [
    .up,
    .down,
    .left,
    .right
]
```

**Comment by MZabih** [comment]
@benliong  did you get any solution to this issue?

**Comment by failynsedik** [comment]
Setting margin to 0 worked for me.
